version: "3"

services:
  roguecraft:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    restart: always
    volumes:
      - "./plugins:/data/plugins"
    environment:
      EULA: "TRUE"
      TYPE: "SPIGOT"
      VERSION: "1.20.4"
      SPIGOT_DOWNLOAD_URL: "https://dl.somc.club/spigot-1.20.4.jar"
      MEMORY: 8G
      OPS: "WindMagi"
      LEVEL: world

      RESOURCE_PACK: "https://dl.somc.club/Roguecraft_Resource_Pack_1.0.2.zip"
      RESOURCE_PACK_SHA1: "53738e04c598294977e89e474582e4874404a497"
      RESOURCE_PACK_ENFORCE: "TRUE"

      DATAPACKS: "https://dl.somc.club/Roguecraft_1.0.5.zip"

      SPAWN_PROTECTION: 0
